name: video_sharing_app_new
description: A video sharing application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.15.1
  firebase_auth: 4.9.0
  cloud_firestore: 4.9.1
  provider: ^6.1.1
  video_player: ^2.8.1
  file_picker: ^6.1.1
  http: ^1.1.0
  crypto: ^3.0.0
  
  #cludeflare r2 SDK
  amazon_cognito_identity_dart_2: ^3.5.0 
  aws_s3_api: ^2.0.0
  path: ^1.8.0
  mime: ^1.0.4

  #file uploader
  ffmpeg_kit_flutter: ^5.1.0
  path_provider: ^2.1.1
  video_compress: ^3.1.2
  path_provider_platform_interface: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true